#!/usr/bin/env node

const contentful = require("contentful-management");
const { CONTENTFUL_ACCESS_TOKEN: accessToken, SJ_SPACE_ID: spaceId } =
  process.env;
const blogPostContentTypeId = "2wKn6yEnZewu2SCCkus4as";
const defaultLocale = "en-US";

const client = contentful.createClient({
  accessToken,
});

if (process.argv.length !== 4) {
  throw new Error("Please provide a headline and a URL");
}

const [, , headline, url] = process.argv;

async function main() {
  const space = await client.getSpace(spaceId);
  const environment = await space.getEnvironment("master");
  const weeklies = await environment.getEntries({
    content_type: blogPostContentTypeId,
    "fields.title[match]": "Web Weekly #",
    "sys.publishedCounter": "0",
    order: "sys.createdAt",
  });

  const nextWeekly = weeklies.items[0];

  if (!nextWeekly) {
    return console.log("No `Web Weekly` found?");
  }

  nextWeekly.fields.body[defaultLocale] =
    nextWeekly.fields.body[defaultLocale] + `\n\n### ${headline}\n\n${url}`;

  await nextWeekly.update();

  console.log(`"${nextWeekly.fields.title[defaultLocale]}" updated!`);
}

main();
