#!/usr/bin/env sh

# Big thanks to @duboiss
# https://github.com/stefanjudis/dotfiles/pull/5#issuecomment-1140508670

if [ -d "./.git" ]; then
  git branch |
  grep --invert-match '\*' |
  grep --invert-match "master" |
  cut -c 3- |
  fzf --height 40% --multi --preview="git log {} --" |
  xargs git branch --delete --force
else
  echo "Error: there's no .git dir"
  exit 1
fi
