#!/usr/bin/env sh

if [ -d "./.git" ]; then
  selected_branch=$(git branch -vv | fzf | sed -e 's/^[[:space:]]*//')

  if [ -n "$selected_branch" ]; then
    branch_name="${selected_branch%% *}"
    git checkout "$branch_name"
  else
    echo "Exit: You haven't selected a branch..."
  fi
else
  echo "Error: There's no .git dir..."
  exit 1
fi
